### ISSUE TITLE
Investigate why non-dev scenarios now requires JDBC configuration

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#379]
### Describe the bug

As reported in Slack:

> for non-dev it did not require any `quarkus.datasource.jdbc.url` in the past, but now it fails because none is provided.

That's why we disabled the tests temporarily: #378 

### Expected behavior

Non-dev scenarios should not require persistence configuration

### Actual behavior

Our ephemeral scenarios are failing since the image now apparently requires JDBC configuration.

### How to Reproduce?

See the given test case #378

**Comment by jordigilh** [comment]
Note this only happens with the callbackstatetimeouts workflow.

**Comment by ricardozanini** [comment]
> Note this only happens with the callbackstatetimeouts workflow.

This is rather puzzling. Let's wait for @wmedvede assessment on this one.

**Comment by jordigilh** [comment]
> > Note this only happens with the callbackstatetimeouts workflow.
> 
> This is rather puzzling. Let's wait for @wmedvede assessment on this one.

Could be in others, but so far I've only found it in this workflow during the e2e test execution.

**Comment by wmedvede** [comment]
Some results for the record:



1. I have created this PL


```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  build:
    template:
    config:
      strategyOptions:
        KanikoBuildCacheEnabled: "true"
  services:
    dataIndex:
      enabled: true
    jobService:
      enabled: true
```

2. I can see that ephemeral DI and JS where deployed well as expected. Positive health-checks, etc.

3. I have deployed the callbackstatetimeouts WF, the deployment was successful, and this properties where generated.
With the deployment above, since no extra stuff is added, an ephemeral deployment is assumed for the WF too.

The following properties where generated, and we can see that no jdbc url was produced as expected.
The workflow starts fine, I the process definition is registered well in the DI too.


	"application.properties": "kogito.events.usertasks.enabled = false
		kogito.service.url = http://callbackstatetimeouts.usecase1
		quarkus.http.port = 8080
		quarkus.http.host = 0.0.0.0
		org.kie.kogito.addons.knative.eventing.health-enabled = false
		quarkus.devservices.enabled = false
		quarkus.kogito.devservices.enabled = false
		kogito.events.processdefinitions.enabled = true
		kogito.events.processinstances.enabled = true
		mp.messaging.outgoing.kogito-job-service-job-request-events.connector = quarkus-http
		mp.messaging.outgoing.kogito-job-service-job-request-events.url = http://sonataflow-platform-jobs-service.usecase1/v2/jobs/events
		mp.messaging.outgoing.kogito-processdefinitions-events.url = http://sonataflow-platform-data-index-service.usecase1/definitions
		mp.messaging.outgoing.kogito-processinstances-events.url = http://sonataflow-platform-data-index-service.usecase1/processes
		"
}

**Comment by jordigilh** [comment]
> Some results for the record:
> 
>     1. I have created this PL
> 
> 
> ```
> apiVersion: sonataflow.org/v1alpha08
> kind: SonataFlowPlatform
> metadata:
>   name: sonataflow-platform
> spec:
>   build:
>     template:
>     config:
>       strategyOptions:
>         KanikoBuildCacheEnabled: "true"
>   services:
>     dataIndex:
>       enabled: true
>     jobService:
>       enabled: true
> ```
> 
>     2. I can see that ephemeral DI and JS where deployed well as expected. Positive health-checks, etc.
> 
>     3. I have deployed the callbackstatetimeouts WF, the deployment was successful, and this properties where generated.
>        With the deployment above, since no extra stuff is added, an ephemeral deployment is assumed for the WF too.
> 
> 
> The following properties where generated, and we can see that no jdbc url was produced as expected. The workflow starts fine, I the process definition is registered well in the DI too.
> 
> ```
> "application.properties": "kogito.events.usertasks.enabled = false
> 	kogito.service.url = http://callbackstatetimeouts.usecase1
> 	quarkus.http.port = 8080
> 	quarkus.http.host = 0.0.0.0
> 	org.kie.kogito.addons.knative.eventing.health-enabled = false
> 	quarkus.devservices.enabled = false
> 	quarkus.kogito.devservices.enabled = false
> 	kogito.events.processdefinitions.enabled = true
> 	kogito.events.processinstances.enabled = true
> 	mp.messaging.outgoing.kogito-job-service-job-request-events.connector = quarkus-http
> 	mp.messaging.outgoing.kogito-job-service-job-request-events.url = http://sonataflow-platform-jobs-service.usecase1/v2/jobs/events
> 	mp.messaging.outgoing.kogito-processdefinitions-events.url = http://sonataflow-platform-data-index-service.usecase1/definitions
> 	mp.messaging.outgoing.kogito-processinstances-events.url = http://sonataflow-platform-data-index-service.usecase1/processes
> 	"
> ```
> 
> }

That works as well for me, since the WF uses an ephemeral instance. Have you tried with a production profile in the workflow?

**Comment by wmedvede** [comment]
@jordigilh 
The workflow is like this, so should default to Prod.

apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: callbackstatetimeouts
  annotations:
    sonataflow.org/description: Callback State Timeouts Example k8s
    sonataflow.org/version: 0.0.1
spec:
  flow:
    start: PrintStartMessage
    events:

**Comment by jordigilh** [comment]
> @jordigilh The workflow is like this, so should default to Prod.
> 
> apiVersion: sonataflow.org/v1alpha08 kind: SonataFlow metadata: name: callbackstatetimeouts annotations: sonataflow.org/description: Callback State Timeouts Example k8s sonataflow.org/version: 0.0.1 spec: flow: start: PrintStartMessage events:

Weird. Yes it should default to a production profile if none is specified. I use [this one](https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/test/testdata/platform/services/prod/postgreSQL/sonataflow/04-sonataflow_callbackstatetimeouts.sw.yaml) and it fails to start because it's missing the jdbc connection url:
```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: callbackstatetimeouts
  annotations:
    sonataflow.org/description: Callback State Timeouts Example k8s
    sonataflow.org/version: 0.0.1
    sonataflow.org/profile: prod
```

The strange thing is that it was not failing before and I don't think the code that handles this has changed recently.

So you're saying that this WF now requires persistence, either it uses ephemeral if none provided or it will use an existing service otherwise. I'm fine if that's the case, but I need a WF that does not have such requirement for the platform testing. Is there any WF in the tech demo repository that can be used to validate along with DI and JS?

**Comment by wmedvede** [comment]
more updates..., so, after pruning images locally, cleaning, and restarting minikube, these manual steps worked fine.

1) install this platform:
```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  build:
    template:
    config:
      strategyOptions:
        KanikoBuildCacheEnabled: "true"
  services:
    dataIndex:
      enabled: true
    jobService:
      enabled: true
```

2) install the workflow:

```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: callbackstatetimeouts
  annotations:
    sonataflow.org/description: Callback State Timeouts Example k8s
    sonataflow.org/version: 0.0.1
    sonataflow.org/profile: prod
spec:
  flow:
    start: PrintStartMessage
```


3) ephemeral DI and JS are working ok, positive health checks

4) I was posible to create a WF instance, and this time, jobs are properly registered in the DI, process definitions and events too, and I can see in the logs 

Installed features: [cache, cdi, jackson-jq, kogito-addon-events-process-extension, **kogito-addon-jobs-knative-eventing-extension**, kogito-addon-knative-eventing-extension, kogito-addon-kubernetes-extension, kogito-addon-messaging-extension, kogito-addon-microprofile-config-service-catalog-extension, kogito-addon-process-management-extension, kogito-addon-source-files-extension, kogito-addons-quarkus-knative-serving, kogito-serverless-workflow, kubernetes, kubernetes-client, qute, reactive-routes, rest-client, rest-client-jackson, resteasy, resteasy-jackson, security, security-properties-file, smallrye-context-propagation, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-http, vertx]



5) WF properties looks like this, which is good, and no jdbc url is generated, which is ok, since no WF peristence is configured.

{
	"application.properties": "kogito.events.usertasks.enabled = false
		kogito.service.url = http://callbackstatetimeouts.usecase1
		quarkus.http.port = 8080
		quarkus.http.host = 0.0.0.0
		org.kie.kogito.addons.knative.eventing.health-enabled = false
		quarkus.devservices.enabled = false
		quarkus.kogito.devservices.enabled = false
		kogito.events.processdefinitions.enabled = true
		kogito.events.processinstances.enabled = true
		mp.messaging.outgoing.kogito-job-service-job-request-events.connector = quarkus-http
		mp.messaging.outgoing.kogito-job-service-job-request-events.url = http://sonataflow-platform-jobs-service.usecase1/v2/jobs/events
		mp.messaging.outgoing.kogito-processdefinitions-events.url = http://sonataflow-platform-data-index-service.usecase1/definitions
		mp.messaging.outgoing.kogito-processinstances-events.url = http://sonataflow-platform-data-index-service.usecase1/processes
		"
}


It looks to be working fine.
