### ISSUE TITLE
Enhance SonataFlowClusterPlatform.spec so it better communicates which settings are used by workflows cluster-wide

### ISSUE THREAD

**Issue by tchughesiv** [apache/incubator-kie-kogito-serverless-operator#380]
### Description

Enhance the api to better communicate to the user which platform settings are being applied to workflows cluster-wide. If possible, allow the user to choose the type(s) of platform setting applied (services, build, etc). However, this should be limited/controlled by the operator. Only specific settings should be candidates. For example `services` and, potentially, `build`.

### Implementation ideas

Create a new string array at `spec.enabledSettings` (or something similar) that defines which platform settings are being exposed to workflows cluster-wide. Leverage CRD validation to restrict this slice to certain *exact* values... in our case `services`, and potentially `build` in the future.
```golang
type SonataFlowClusterPlatformSpec struct {
	PlatformRef SonataFlowPlatformRef `json:"platformRef"`

	// +kubebuilder:validation:UniqueItems=true
	// +kubebuilder:validation:Enum=services;build
	EnabledSettings *[]string `json:"enabledSettings,omitempty"`
}
```
```yaml
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  name: cluster-platform
spec:
  platformRef:
    name: sonataflow-platform
    namespace: central-platform-ns
  enabledSettings:
  - services
  - build (in the future?)
```

If `spec.enabledSettings = nil`, maybe we add `services` to the array by default?

**Comment by tchughesiv** [comment]
i'm not sure `enabledSettings` is the right name for this new field. Maybe just `enabled`? others?

**Comment by tchughesiv** [comment]
what about -
```yaml
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  name: cluster-platform
spec:
  platformRef:
    name: sonataflow-platform
    namespace: central-platform-ns
  enabled:
    forWorkflows:
    - services
    - build (in the future?)
```

**Comment by tchughesiv** [comment]
@masayag 
> Shouldn't the enabled services be determined by the platform configured in `platformRef`? What will be the use case to configure the persistence, DI, and JS and decide not to use them at the cluster-level?

Yes and no. The purpose of the SonataFlowClusterPlatform when introduced with https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/345 was to enable specific cluster-wide configs (in this case "supporting services") for **workflow** config consumption, It was NOT intended/designed for service config consumption (DI/JS). This means that service configs, e.g. pod resources & persistence, should only ever be affected by the active platform CR in their own namespace.

Additionally, when we started this effort, the idea of a shareable persistence configuration at `platform.spec.persistence` wasn't yet a thing. That is a new feature whose PR is still outstanding https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/372.

So, to take things a step further, it's important to be *very* careful about what other platform configs are enabled cluster-wide for workflow consumption in the future. For example, in my opinion the new global persistence configs in https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/372 should NOT be enabled cluster-wide for workflows. It would result in a major security risk for users if our operator is providing creds and connectivity information haphazardly to every namespace in the cluster. Persistence should only be set at the namespace level which ensures that only those who *should* have the creds are the ones using them.

That said, something like `platform.spec.build` configs might be a good cluster-level candidate at some point.

The original discussion on this can be read here https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/372#discussion_r1474153068 and is the reason we created this issue. @ricardozanini wanted to make it more clear (beyond api field descriptions) in the SonataFlowClusterPlatform which "capabilities" are being set cluster-wide, and that the workflows are the main consumers of these "capabilities".

This seems like a good approach which would also allow users to customize "capabilities" if they so choose. It would also open the door for future cluster-wide "service" configs, which could be enabled separately w/ a `spec.serviceCapabilities`, for example.

> 
> What about including persistence in that list (in addition to services and build)? For the naming, throwing out this options:
> 
> ```
> spec:
>   supportedFeatures:
>     - services
>     - build
>     - persistence
> ```

If we were to implement this design I think we should stick with `services` at first (since its already been implemented), but this design would allow us to support additional cluster-wide workflow-related configs in the future.

> 
> or `workflowFeatures`, `workflowCapabilities`

I think I like `workflowCapabilities` the best so far, but still not sure.

**Comment by tchughesiv** [comment]
@masayag @ricardozanini ??
```yaml
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  name: cluster-platform
spec:
  platformRef:
    name: sonataflow-platform
    namespace: central-platform-ns
  capabilities:
    workflow:
    - services
    - build (in the future?)
```
