### ISSUE TITLE
Default schema used for workflow persistence in postgresql is 'default' instead of 'public'

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-serverless-operator#408]
### Describe the bug

When we configure the persistence for a workflow like below, and we don't set any databaseSchema name, the operator is creating a jdbc url like this:
	
jdbc:postgresql://postgres.usecase3-persistence:5432/sonataflow?currentSchema=default

A schema with name 'default' is configured, however this schema don't exists. Instead, by default postgresql has a schema with the name 'public'.

So, for that case, we should:

1. Set no schema at all, create the url like this: jdbc:postgresql://postgres.usecase3-persistence:5432/sonataflow and the 'public' schema should be automatically picked up.

2. Simply use 'public' instead of 'default'
	
3. Use the workflow name as the schema name. (This last option I believe it was already discussed during development and discarded)

```
spec:
  persistence:
    postgresql:
      secretRef:
        name: postgres-secrets
        userKey: POSTGRES_USER
        passwordKey: POSTGRES_PASSWORD
      serviceRef:
        name: postgres
        databaseName: sonataflow
```

### Actual behavior

Right now, when we create a workflow instance an error is produced since the queries are executed against the configured 'default' schema that don't exists.
