### ISSUE TITLE
Support of security properties in the sonataflowplatforms for Workflows and Data Index

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-serverless-operator#436]
### Description

In order to ease the security settings of workflows, setting the [quarkus.http.auth.permission](https://quarkus.io/version/3.8/guides/all-config#quarkus-vertx-http_quarkus-http-auth-permission-permissions-enabled) and [quarkus.http.auth.policy](https://quarkus.io/version/3.8/guides/all-config#quarkus-vertx-http_quarkus-http-auth-policy-role-policy-roles-allowed) properties at runtime (once the runtime will be using a quarkus version allowing it) in the `sonataflowplatforms` CR and then have those properties propagated to all running workflows (via `props` or `managed` configmap) would be of great help.

Same applied for [quarkus.oidc](https://quarkus.io/version/3.8/guides/all-config#quarkus-oidc_quarkus-oidc-auth-server-url) properties in order to only setup the provider connection once. 
Need to consider [quarkus.oidc.credentials.secret](https://quarkus.io/version/3.8/guides/all-config#quarkus-oidc_quarkus-oidc-credentials-secret), which should be in a secret and not a configmap but nonetheless provided to the workflows.

In addition, the Data Index having (at least) the `/graphql` exposing information about the workflows, it shall also be protected, so having a separation between properties for the DataIndex and the Workflows is needed.

For the provider, the clients may not be the same, so same applies.

Relevant doc for setting security config in application.properties: https://quarkus.io/guides/security-authorize-web-endpoints-reference

**Comment by ricardozanini** [comment]
I'll add a few implementation ideas here so others can chime in. If needed, I can create a design doc.

So I think we can have a `.spec.properties.flow` within the `SonataFlowPlatform` interface. This attribute can be a map of a complex object derived from the [Kubernetes Env Var](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#envvar-v1-core) API, meaning that the propagated properties can be defined directly to the CR. Example:

```yaml
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
    properties:
        flow:
         - name: quarkus.http.auth.permission
            value: myValueForTheProperty
         - name: quarkus.http.auth.policy
            valueFrom:
                secretKeyRef: my-secret
                    keyName: my-policy
                    optional: false
         - name: quarkus.other.property
            valueFrom:
                configMapRef: my-config-map
                    keyName: my-property
                    optional: false 
```

So one can either set the value directly, from a secret or configMap.

We use `.spec.properties.flow` to have some room to add properties for the Data Index, or any other supporting service or future actor in the platform.

## Cluster Platform
In the cluster platform, we are going to set the `.spec.capabilities` to `properties.flow` by default. So one can set to an empty value if the cluster platform does not propagate the properties to the whole cluster.

@masayag @gabriel-farache @wmedvede @jakubschwan please let me know what you think.
