### ISSUE TITLE
Add custom configuration to the DI and JS for operator managed deployments

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-serverless-operator#445]
### Description

With the current implementation of the operator managed DI and JS deployment, it's not possible for users to configure particular settings that could apply additionally to the configurations injected by the operator.

However there might be situations where uses might need to fine tune a particular deployment. In this Jira we must provide this ability.

### Implementation ideas

We will use the already existing ability of defining the "container" settings at the SonataFlowPlatform service specification, and grab potential user provided env variables from there. As part of this process, we must be careful to don't override the operator managed env vars. 

Example of such configuration:

```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    jobService:
      enabled: true
      persistence:
        postgresql:
          jdbcUrl: jdbc:postgresql://postgres:5432/sonataflow?currentSchema=jobs-service
          secretRef:
            name: postgres-secrets
            userKey: POSTGRES_USER
            passwordKey: POSTGRES_PASSWORD
      podTemplate:
        container:
          env:
            - name: MY_VAR1                                                     (user tuning)
              value: MY_VAR_VALUE1  
            - name: MY_VAR2                                                     (user tuning)
              value: MY_VAR_VALUE2
            - name: QUARKUS_DATASOURCE_PASSWORD   (note, this value won't be applied since it's managed by the operator)
              value: WHATEVER_VALUE
```

_No response_
