### ISSUE TITLE
Supporting service don't inherit platform persistence when the current service persistence is empty

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-serverless-operator#476]
### Describe the bug

Given a configuration like below, we have that data-index and jobs-service must inherit the persistence configuration from the platform. However if we set for example persitence: {} for the jobs service, we get an segmentation error at deploytime.

```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    # no persistence is defined for the DI, it will take it from the SFP if any.
    dataIndex:
      enabled: true
    jobService:
      # no persistence is defined for the JS, it will take it from the SFP if any.
      enabled: true
      persistence: {}
  persistence:
    postgresql:
      secretRef:
        name: postgres-secrets
        userKey: POSTGRESQL_USER
        passwordKey: POSTGRESQL_PASSWORD
      serviceRef:
        name: postgres
        databaseName: sonataflow
```

### Expected behavior

The deployment of both services must work an take the persistence configuration from the platform.
