### ISSUE TITLE
Error when deploying a WF with the dev profile in a SPF that has persistence configured

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-serverless-operator#520]
### Describe the bug

When we deploy a workflow with the dev profile in a namespace that already has deployed a SPF with persistence configured, e.g.:

```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  persistence:
    postgresql:
      secretRef:
        name: postgres-secrets
        userKey: POSTGRESQL_USER
        passwordKey: POSTGRESQL_PASSWORD
      serviceRef:
        name: postgres
        databaseName: sonataflow
```

It looks like some of the persistence related configurations are applied to the WF producing an error. Note that a WF with the dev profile shouldn't take any persistence configuration from the SFP.

To reproduce:

1) deploy a SFP with persistence configured in a namespace my-namespace
2) deploy a WF with the dev profile in my-namespace
3) see the logs for the WF's Pod for the errors.
